defaults: &defaults
  host: localhost
  port: 27017
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  host: hydra.mongohq.com
  port: 10044
  username: peruinfo
  password: yaraher
  database: PeruInfoProduction
  uri: <%= ENV['MONGOHQ_URL'] %>

test:
  <<: *defaults
  database: locomotive_test

# set these environment variables on your prod server
production:
  host: hydra.mongohq.com
  port: 10044
  username: peruinfo
  password: yaraher
  database: PeruInfoProduction
  uri: <%= ENV['MONGOHQ_URL'] %>

  # other settings for production

  # host: <%= ENV['MONGOID_HOST'] %>
  # port: <%= ENV['MONGOID_PORT'] %>
  # username: <%= ENV['MONGOID_USERNAME'] %>
  # password: <%= ENV['MONGOID_PASSWORD'] %>
  # database: <%= ENV['MONGOID_DATABASE'] %>

  # heroku
  # uri: <%= ENV['MONGOHQ_URL'] %>

